### ISSUE TITLE
enable discussions?

### ISSUE THREAD

**Issue by ghostsquad** [derlin/reading-stats#1]
I love this idea, also found this from the dev.to article. I've been looking for a side project to build up some skills including frontend and the challenge of free or cheap is great. I like reading too, but it turns out, it happens to be articles like this. But maybe it really needs to be more books.

It's late right now, but I'd like to talk more about this at another time.

**Comment by derlin** [comment]
Great to hear! I enabled discussion, I still have to set it up properly. I will let you know!

**Comment by derlin** [comment]
I started a discussion here: https://github.com/derlin/reading-stats/discussions/2
